# Generated by Django 4.1.6 on 2023-02-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('persian_name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='province.province')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
    ]
