# Generated by Django 4.1.5 on 2023-02-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0002_alter_province_table'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='province.province'),
        ),
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
    ]
