version: '3'

services:
  django:
    container_name: django
    volumes:
      - static:/app/media/static
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks: [ selloora ]
volumes:
  static:
    driver: local
networks:
  selloora:
    external: true