version: '3.9'

services:
  django:
    container_name: django
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks: [ docker-stack_selloora ]
volumes:
  static:
    driver: local
networks:
  docker-stack_selloora:
    external: true