# Generated by Django 4.1.6 on 2023-02-10 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'landing_contacts',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LandingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('media', models.ImageField(upload_to='landing/articles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'landing_articles',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'landing_config',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LandingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('media', models.ImageField(upload_to='landing/categories')),
                ('articles', models.ManyToManyField(related_name='categories', to='landing.landingarticle')),
            ],
            options={
                'db_table': 'landing_categories',
                'ordering': ('-id',),
            },
        ),
    ]
