# Generated by Django 4.1.6 on 2023-02-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='LandingContact',
        ),
        migrations.RenameModel(
            old_name='LandingConfig',
            new_name='LandingSetting',
        ),
    ]
