# Generated by Django 4.1.6 on 2023-02-10 21:44

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_contact_landingcontact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingarticle',
            old_name='author',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='landingarticle',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landingarticle',
            name='media',
            field=models.ImageField(upload_to=landing.models.article_directory_path),
        ),
        migrations.AlterField(
            model_name='landingarticle',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='landingcategory',
            name='media',
            field=models.ImageField(upload_to=landing.models.category_directory_path),
        ),
    ]
