# Generated by Django 4.1.6 on 2023-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_rename_author_landingarticle_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingsetting',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='landingsetting',
            name='faq',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingsetting',
            name='pricing',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
