# Generated by Django 4.1.6 on 2023-02-11 15:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_landingsetting_options_landingsetting_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingarticle',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
