# Generated by Django 4.1.6 on 2023-02-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_landingarticle_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingarticle',
            old_name='user_id',
            new_name='user',
        ),
    ]
