# Generated by Django 4.1.5 on 2023-02-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_user_alter_media_table'),
        ('user', '0002_alter_user_city_alter_user_province_alter_user_table'),
        ('shop', '0002_alter_shop_media_alter_shop_theme_alter_shop_user_and_more'),
        ('product_category', '0002_alter_productcategory_shop_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.product'),
        ),
        migrations.AlterField(
            model_name='option',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='user.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='medias',
            field=models.ManyToManyField(related_name='products', to='media.media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_categories',
            field=models.ManyToManyField(related_name='products', to='product_category.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.user'),
        ),
        migrations.AlterModelTable(
            name='option',
            table='options',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
