# Generated by Django 4.1.6 on 2023-02-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('persian_name', models.CharField(max_length=150)),
                ('english_name', models.CharField(max_length=150)),
                ('COD', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
    ]
