# Generated by Django 4.1.5 on 2023-02-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('persian_name', models.CharField(max_length=150)),
                ('english_name', models.CharField(max_length=150)),
                ('COD', models.CharField(max_length=150)),
            ],
        ),
    ]
