# Generated by Django 4.1.5 on 2023-02-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='province',
            table='provinces',
        ),
    ]
