# Generated by Django 4.1.6 on 2023-02-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('value', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('percent', 'percent'), ('amount', 'amount')], max_length=255)),
                ('model', models.CharField(choices=[('shop', 'shop'), ('product', 'product')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discounts',
            },
        ),
    ]
