# Generated by Django 4.1.6 on 2023-02-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_category', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ManyToManyField(related_name='articles', to='article_category.articlecategory'),
        ),
    ]
