# Generated by Django 4.1.5 on 2023-02-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_user_alter_media_table'),
        ('user', '0002_alter_user_city_alter_user_province_alter_user_table'),
        ('article_category', '0002_alter_articlecategory_shop_and_more'),
        ('shop', '0002_alter_shop_media_alter_shop_theme_alter_shop_user_and_more'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.ManyToManyField(related_name='articles', to='article_category.articlecategory'),
        ),
        migrations.AlterField(
            model_name='article',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='media.media'),
        ),
        migrations.AlterField(
            model_name='article',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='user.user'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
