# Generated by Django 4.1.6 on 2023-02-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_category',
            new_name='article_categories',
        ),
    ]
