# Generated by Django 4.1.5 on 2023-02-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_article_category_alter_article_media_and_more'),
        ('shop', '0002_alter_shop_media_alter_shop_theme_alter_shop_user_and_more'),
        ('user', '0002_alter_user_city_alter_user_province_alter_user_table'),
        ('article_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='article.article'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='user.user'),
        ),
        migrations.AlterModelTable(
            name='articlecomment',
            table='article_comments',
        ),
    ]
