# Generated by Django 4.1.6 on 2023-02-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['-created_at']},
        ),
    ]
