# Generated by Django 4.1.5 on 2023-02-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_user_alter_media_table'),
        ('user', '0002_alter_user_city_alter_user_province_alter_user_table'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='media.media'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='theme',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shop.theme'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='user.user'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='media.media'),
        ),
        migrations.AlterModelTable(
            name='shop',
            table='shops',
        ),
        migrations.AlterModelTable(
            name='theme',
            table='themes',
        ),
    ]
