# Generated by Django 4.1.6 on 2023-02-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-created_at']},
        ),
    ]
