# Generated by Django 4.1.5 on 2023-02-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_province_alter_city_table'),
        ('province', '0002_alter_province_table'),
        ('user', '0002_alter_user_city_alter_user_province_alter_user_table'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='city.city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='province.province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.user'),
        ),
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
    ]
