# Generated by Django 4.1.5 on 2023-02-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_media_alter_shop_theme_alter_shop_user_and_more'),
        ('user', '0002_alter_user_city_alter_user_province_alter_user_table'),
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='user.user'),
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_categories',
        ),
    ]
