# Generated by Django 4.1.6 on 2023-02-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at']},
        ),
    ]
