# Generated by Django 4.1.5 on 2023-02-01 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('man', 'man'), ('woman', 'woman')], max_length=5, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(max_length=255, unique=True)),
                ('expire_at', models.DateField(default=datetime.date(2025, 1, 1))),
                ('status', models.CharField(choices=[('ok', 'ok'), ('block', 'block')], default='ok', max_length=5)),
                ('verify_code', models.CharField(blank=True, max_length=255, null=True)),
                ('cart_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shaba', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_send_sms_at', models.DateTimeField(blank=True, null=True)),
                ('gallery_id', models.IntegerField(blank=True, null=True)),
                ('profile_photo_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='province.province')),
            ],
        ),
    ]
