# Generated by Django 4.1.5 on 2023-02-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_city_alter_user_province_alter_user_table'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='user.user'),
        ),
        migrations.AlterModelTable(
            name='media',
            table='media',
        ),
    ]
