# Generated by Django 4.1.6 on 2023-02-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='media',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
