# Generated by Django 4.1.6 on 2023-02-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_media_updated_at_media_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='media',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
