# Generated by Django 4.1.6 on 2023-02-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(null=True)),
                ('is_answer', models.BooleanField(default=False)),
                ('visited', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='media.media')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
