# Generated by Django 4.1.5 on 2023-02-01 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('discount', '0001_initial'),
        ('product', '0001_initial'),
        ('address', '0001_initial'),
        ('shop', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('total_product_price', models.IntegerField()),
                ('total_discount_price', models.IntegerField()),
                ('total_tax_price', models.IntegerField()),
                ('total_product_discount_price', models.IntegerField()),
                ('total_final_price', models.IntegerField()),
                ('send_price', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('wait_for_pay', 'WaitForPay'), ('wait_for_try_pay', 'WaitForTryPay'), ('paid', 'Paid'), ('wait_for_sender', 'WaitForSender'), ('wait_for_delivery', 'WaitForDelivery'), ('delivered', 'Delivered'), ('returned_timeout', 'ReturnedTimeout'), ('wait_for_accept_returned', 'WaitForAcceptReturned'), ('reject_returned', 'RejectReturned'), ('wait_for_sender_returned', 'WaitForSenderReturned'), ('delivered_returned', 'DeliveredReturned'), ('wait_for_returned_pay_back', 'WaitForReturnedPayBack'), ('returned_paid', 'ReturnedPaid')], default='wait_for_pay', max_length=50)),
                ('description', models.TextField(null=True)),
                ('package_size', models.CharField(max_length=255, null=True)),
                ('tracking_code', models.CharField(max_length=255, null=True)),
                ('courier', models.CharField(max_length=255, null=True)),
                ('last_update_status_at', models.DateTimeField(default=datetime.datetime.now)),
                ('weight', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('discount_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.discount')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('quantity', models.IntegerField()),
                ('raw_price', models.IntegerField()),
                ('raw_price_option', models.IntegerField()),
                ('raw_price_count', models.IntegerField()),
                ('raw_price_option_count', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('off_price', models.IntegerField()),
                ('off_price_option', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('new_price_option', models.IntegerField()),
                ('final_raw_price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('has_option', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.option')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
