name: ci_selloora_main_backend

on:
  push:
    tags:
      - 'release-*'


jobs:
  # build docker image and push to https://registry.hamyarsale.ir custom registry with this username and password: amirex128 and a6766581
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.hamyarsale.ir
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: selloora_main_backend:latest